version: '3.5'
services:

  api1: &api
    image: lcs-rinha-api
    hostname: api1
    ports:
      - '81:3000'
    environment:
      API_INSTANCE: api1
      CLUSTER: true
      CLUSTER_WORKERS: 3
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.6GB'
    # ulimits:
    #   nproc: 1000000
    #   nofile:
    #     soft: 1000000
    #     hard: 1000000
    networks:
      - rinha-network

  api2:
    <<: *api
    hostname: api2
    ports:
      - '82:3000'
    environment:
      API_INSTANCE: api2

  nginx: # Load Balancer
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
    # ulimits:
    #   nproc: 1000000
    #   nofile:
    #     soft: 1000000
    #     hard: 1000000
    networks:
      - rinha-network

  db: # Banco de dados
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.5GB'
    networks:
      - rinha-network

volumes:
  db-data:

networks:
  rinha-network:
    external: true
  default:
    driver: bridge

