version: '3.5'
services:

  api1: &api
    image: lcs-rinha-api
    hostname: api1
    ports:
      - '81:3000'
    environment:
      API_INSTANCE: api1
      CLUSTER_WORKERS: 3
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.6GB'
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      - rinha-network

  api2:
    <<: *api
    hostname: api2
    ports:
      - '82:3000'
    environment:
      API_INSTANCE: api2
      CLUSTER_WORKERS: 3

  nginx: # Load Balancer
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'

    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      - rinha-network

  db: # Banco de dados
    image: postgres
    command: postgres -c 'max_connections=450' -c 'log_error_verbosity=terse' -c 'client_min_messages=error'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '1.5GB'
    networks:
      - rinha-network

networks:
  rinha-network: