version: '3.5'
services:
  api1: &api
    image: lcs-rinha-api
    environment:
      API_INSTANCE: api1
      CLUSTER_WORKERS: 10
      PORT: 8080
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.6GB'
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    network_mode: host

  api2:
    <<: *api
    environment:
      API_INSTANCE: api2
      CLUSTER_WORKERS: 10
      PORT: 8081

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api1
  #     - api2
  #   ports:
  #     - "9999:9999"
  #   ulimits:
  #     nproc: 1000000
  #     nofile:
  #       soft: 1000000
  #       hard: 1000000
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.15'
  #         memory: '0.3GB'
  #   network_mode: host

  db:
    image: postgres
    command: postgres -c 'max_connections=450' -c 'log_error_verbosity=terse' -c 'client_min_messages=error'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '1.5GB'
    network_mode: host

volumes:
  db-data:

