version: '3.5'
services:
  api1: &api
    image: lcs-rinha-api
    environment:
      API_INSTANCE: api1
      CLUSTER_WORKERS: 10
      PORT: 8080
    env_file:
      - .env
    network_mode: host
    depends_on:
      - db
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.6GB'

  api2:
    <<: *api
    environment:
      API_INSTANCE: api2
      CLUSTER_WORKERS: 10
      PORT: 8081

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'

  db:
    image: postgres
    command: postgres -c 'max_connections=450' -c 'log_error_verbosity=terse' -c 'client_min_messages=error'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '1.5GB'

volumes:
  db-data: